- name: PROVISIONING INSTANCE EC2 NEWAPP
  amazon.aws.ec2:
    key_name: "{{ keypair }}"
    group: "{{ sg_name }}"
    instance_type: "{{ instance_type }}"
    image: "{{ image }}"
    region: "{{ region }}"
    wait: yes
    wait_timeout: 400
    volumes:
      - device_name: /dev/xvda
        volume_type: gp2
        volume_size: 50
        delete_on_termination: true
    count: "{{ count }}"
    instance_tags:
      owner: "{{ tag_owner }}"
      team: "{{ tag_team }}"
      Name: NewApplication    
    monitoring: no
    vpc_subnet_id: "{{ subnet_id }}"
    assign_public_ip: yes
  register: ec2

- name: ADD IP IN FILE INVENTORY HOST
  local_action: lineinfile
    dest="./hosts"
    regex={{ item.public_ip }}
    insertafter="[webservers]" line="{{ item.public_ip }} ansible_ssh_user=centos ansible_ssh_private_key_file=/home/diego/Documentos/ansible/ansibletest.pem"
  with_items: "{{ ec2.instances }}" 
  
- name: Wait 120 seconds, but only start checking after 60 seconds
  wait_for_connection:
    delay: 100
    timeout: 60
